### ISSUE TITLE
Installer (monitor-bo)

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/monitor-back#1]
Potrzebny installer.
Taki, żeby można było jedną komendą (np. `ant install`) postawić serwer aplikacyjny wraz z zainstalowaną na nim aplikacją.

Proponowanym do tego przeze mnie narzędziem jest `ant`.

Zadanie do wykonania w późniejszej fazie projektu.

**Comment by marcinpilat** [comment]
A możę `maven`? To jest następca `ant`'a i raczej wiodące narzędzie w sferze zarządzania budowaniem i deployowania aplikacji. Jakby co, to mogę wziąć na siebie stworzenie archetypu `maven`'a i późniejsze zarządzaniem `pom`'em.

**Comment by kamciak** [comment]
Ja byłbym właśnie za mavenem.

**Comment by salberski** [comment]
No ok, póki co miałem tylko doświadczenie z rozwiązaniem dla appek opartych
o mavena, że ich installer, który wypakuje paczkę z serwerem aplikacyjnym,
następnie zdeployuje appke jest w ancie.
w sumie da się w mavenie tym zarządzić więc spoko, approved ;)

2015-03-11 19:06 GMT+01:00 kamciak notifications@github.com:

**Comment by marcinpilat** [comment]
Biorąc pod uwagę pluginy w mavenie da się prawie wszystko:) Musimy wybrać jeszcze serwer aplikacyjny lub kontener webowy: Jboss/Glassfish lub Tomcat.

**Comment by salberski** [comment]
Tomcat wymuszałby wykorzystanie springa i jego autowiredów zamiast ejb, ale
za to jest dużo lżejszy, tyle że trzeba się z konfiguracją springa pobawić.
GF i JBoss to można na EJBkach, serwery te można potraktować jako all i
one, możliwe ze robota będzie prostsza i szybciej zacznie się pisać mięso.

W dniu 11 marca 2015 23:02 użytkownik Marcin Piłat <notifications@github.com

**Comment by salberski** [comment]
Utworzyłem prosty installer (antowy) dla appki a także wystawiłem pierwszego RESTa 
(przeczytajcie readme - tam są wszystkie informacje)

Póki co wystarczy, jak ktoś będzie bardzo chciał to może przerobić. :)

**Comment by salberski** [comment]
Jakby ktoś mógł przetestować installer i podzielić się wrażeniami, jak czegoś brakuje, albo coś jest niezrozumiałe to piszcie.

**Comment by KamilSzelag** [comment]
Podczas kroku ant install dostaję error:

```
BUILD FAILED
...\monitor-back\monitor-back\installer\build.xml:21: Warning: Could not find file ...\monitor-back\monitor-back\installer\server\tomcat\bin\catalina.bat to copy.
```

**Comment by salberski** [comment]
Ok, rzeczywiście brakuje, jutro dorzucę.

**Comment by salberski** [comment]
Wrzuciłem poprawki, teraz powinno być dobrze. :+1: 
Sprawdźcie proszę.
