### ISSUE TITLE
Pobieranie wiadomości z JMS

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/monitor-back#12]
@Silwest zajmij się proszę tym zadaniem.

Dane, które zostaną odebrane z kolejki powinny zostać zapisane do bazy w niezmienionej formie.

**Comment by Silwest** [comment]
Jako ze nie ma bazy danych, informacja pobierana jest z activeMQ i wyswietlana na wyjsciu. Jedynie co pozostalo to wrzucenie tego do bazy danych.
